### ISSUE TITLE
got error

### ISSUE THREAD

**Issue by mithuncoder** [2O4/pof#1]
pof hello.py -o out.py -f obfuscator BuiltinsObfuscator

usage: obfuscate [-h] [-v] [--raise-exceptions] [-o OUTPUT] [-f FUNCTION]
                 [--logging LOGGING] [-k [KWARGS ...]]
                 [input]
obfuscate: error: unrecognized arguments: BuiltinsObfuscator

please add a example cmd for all obfuscation

**Comment by deoktr** [comment]
Actually I made a mistake, the class used for obfuscation is passed with the `-k` flag. So it should be something like:

```
pof hello.py -o out.py -f obfuscator -k BuiltinsObfuscator
```
